name: GitHub - Activity - Readme

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: GitHub - Activity - Readme

     steps:
      - uses: actions/checkout@v2
      - uses: uses: jamesgeorge007/github-activity-readme@v0.3.6

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
